
paypal:
 client-id: AZGuQXyAY4NsclI3kK8GVF1FKQQ_G_jgESNQDIDed69kB0ESPvJNck8fInAO-prHSeG4ueCCfDZo4qUB
 client-secret: EPRdArqQPNWvZpYPJ18V_D6ls0rcHo2hJsKkXU-hLSE1cFxaEUuLbEWLfVxeUR-l2LfnGVVF8aSy_bW2
 mode: sandbox
